### PR TITLE
Create Sieve-of-Eratosthenes.c++

### LINKED ISSUE #311: Sieve of Eratosthenes in C++
I wish to add Sieve of Eratosthenes in C++ language as a DevIncept contributor

### PR DESCRIPTION
**Pull request by ishikasinha-d**
Closes #311

### CODE REVIEW

**Review by smv1999 — APPROVED** [review]

**Review by smv1999 — CHANGES_REQUESTED** [review]
Don't place the program in Dynamic Programming and also the file name is incorrect. The extension should be .cpp

**Comment by ishikasinha-d** [comment]
@smv1999 okay. Where should I put it then?

**Comment by smv1999** [comment]
> @smv1999 okay. Where should I put it then?

Place it in Numbers folder.

**Comment by ishikasinha-d** [comment]
@smv1999 Placed it in numbers folder and updated extension to cpp. Please review.

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
