### PR TITLE
Circular queue

### PR DESCRIPTION
**Pull request by RC2208**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

yes
### Description

Circular queue using C

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#662 

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Delete the file password_strength_checker.py which is not related to this PR. Also, rename the file as circular_queue.c

**Comment by RC2208** [comment]
Done. Sorry, Idk y they both were coming together in both the pr's

**Comment by Saviour1001** [comment]
@RC2208 you mistakenly deleted the priority queue program as well. Please add it back. The overall PR should just add one file. You changed 2 files , added one and removed one

**Comment by RC2208** [comment]
I added it back. Can you check now?

**Comment by Saviour1001** [comment]
Looks great !! Nice work @RC2208

**Pull request merged**
