### PR TITLE
Red alert solution (codechef problem) in C language.

### PR DESCRIPTION
**Pull request by simranquirky**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Description

Solution to codechef problem-july lunchtime contest in C language

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#851 

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Comment by simranquirky** [comment]
PROBLEM STATEMENT
According to the Meteorological Department, there will be rain in the upcoming N days in the city. Initially, the water level of the city is zero millimetres. The amount of rain on the i-th day can be described by an integer Ai as follows:

If Ai>0, the water level of the city increases by Ai millimetres on the i-th day.
If Ai=0, there is no rain on the i-th day. The water level of the city decreases by D millimetres on such a day. However, if the water level is less than D millimetres before the i-th day, then it becomes zero instead.
There will be a red alert in the city if the water level becomes strictly greater than H millimetres on at least one of the N days. Determine if there will be a red alert.

Input Format
The first line of the input contains a single integer T denoting the number of test cases. The description of T test cases follows.
The first line of each test case contains three space-separated integers N, D and H.
The second line contains N space-separated integers A1,A2,…,AN.
Output Format
For each test case, print a single line containing the string "YES" if there will be a red alert or "NO" otherwise.

**Review by smv1999 — CHANGES_REQUESTED** [review]
Mention the space and time complexity of the approach used. Also, add comments to explain your core logic.

**Comment by simranquirky** [comment]
> Mention the space and time complexity of the approach used. Also, add comments to explain your core logic. 

Ok

**Comment by simranquirky** [comment]
Requested changes has been made @smv1999

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
