### PR TITLE
Added a program in arrays

### PR DESCRIPTION
**Pull request by nikita-jain-01**

### CODE REVIEW

**Review by smv1999 — APPROVED** [review]
Looks good to me :)

**Comment by smv1999** [comment]
@nikita-jain-01 Please note that it is always recommended to commit to a new branch instead of master (main) branch and then push your changes and make a PR. Please refer to [Contributing Guidelines](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md) if you need help in this regard. Please make a note of this for the next PR that you make.

**Comment by nikita-jain-01** [comment]
> @nikita-jain-01 Please note that it is always recommended to commit to a new branch instead of master (main) branch and then push your changes and make a PR. Please refer to [Contributing Guidelines](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md) if you need help in this regard. Please make a note of this for the next PR that you make.

I'll take care of that from now onwards.

**Comment by smv1999** [comment]
Sure @nikita-jain-01 !

**Pull request merged**
