### PR TITLE
cycle detection using java in linked lists

### PR DESCRIPTION
**Pull request by inimitable034**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
issue- #411 

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Comment by inimitable034** [comment]
Successfully added the cycle detection using java in linked lists program.
Do check and update

**Comment by Saviour1001** [comment]
Add more explanation comments, you can add examples, time and space complexities and even more text at the top of the file explaining the intuition.

**Comment by inimitable034** [comment]
> Add more explanation comments, you can add examples, time and space complexities and even more text at the top of the file explaining the intuition.

Sure.
will add soon...

**Review by smv1999 — CHANGES_REQUESTED** [review]
There is an unnecessary extension ".txt' at the end of the file " Data Structures/Linked Lists/Singly Linked List/cycle-detection-using-java.java.txt"

**Comment by inimitable034** [comment]
> There is an unnecessary extension ".txt' at the end of the file " Data Structures/Linked Lists/Singly Linked List/cycle-detection-using-java.java.txt"

Unwanted extension removed.

**Comment by inimitable034** [comment]
Thank you sir @Saviour1001

**Pull request merged**
