### PR TITLE
Python-singly-linked-list-all-operations

### PR DESCRIPTION
**Pull request by aakankshabhende**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?
Yes

### Description
I have added a python program for singly linked list with all operations like inserting deleting from beginning, end at any given index, etc

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Closes : #397

### CODE REVIEW

**Comment by Saviour1001** [comment]
Explain your code and space and time complexities with comments.

**Comment by aakankshabhende** [comment]
Done @Saviour1001 sir

**Comment by Saviour1001** [comment]
Looks great !! Nice work @aakankshabhende !!

**Review by smv1999 — CHANGES_REQUESTED** [review]
Python uses '#' for comments. Just make those changes.

**Comment by aakankshabhende** [comment]
Done @smv1999 sir

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
