### PR TITLE
 0/1 Knapsack using Tabulation method

### PR DESCRIPTION
**Pull request by RAUNAK-PANDEY**

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
When you are suggesting an alternate solution, make sure to create an issue for the same (in future) and also give your alt solution as a separate file.

**Comment by RAUNAK-PANDEY** [comment]
@smv1999  Okay I will take care of it in future . Actually I followed the contributing guidelines there It is not mentioned to create to a issue for alternate approach . Issue is mentioned only for new problem.

**Comment by smv1999** [comment]
> @smv1999 Okay I will take care of it in future . Actually I followed the contributing guidelines there It is not mentioned to create to a issue for alternate approach . Issue is mentioned only for new problem.

Thanks for pointing out, I will add that information.

**Comment by smv1999** [comment]
@RAUNAK-PANDEY , I have received information from the DevIncept team that PRs can be merged even before the actual coding period starts i.e., 10th July. 
So, proceed and make the suggested changes. 

Give your alt solution as a separate file.

**Comment by RAUNAK-PANDEY** [comment]
@smv1999 Please check alt solution for knapsack. I have added a separate file.

**Pull request merged**
