### PR TITLE
Added Decode Ways II (LeetCode) problem

### PR DESCRIPTION
**Pull request by Karnika06**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes.

### Description

Added Decode Ways II problem solution in Strings folder.
Link to the problem: https://leetcode.com/problems/decode-ways-ii/

It is an important problem to practice String Questions.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Comment by Saviour1001** [comment]
mention the issue this PR fixes

**Comment by Saviour1001** [comment]
And you have also deleted a Java file in the PR, please add it back.

**Comment by Karnika06** [comment]
This PR fixes #637 issue

**Comment by Saviour1001** [comment]
Bravo @Karnika06 !!

**Pull request merged**
