### PR TITLE
closes #443 Trapping rain water

### LINKED ISSUE #443: Trapping Rain Water using 3 approaches
I want to add the **Trapping Rain Water** problem using C++ in the Array folder.
Under DCP'21.

I want to add the below approaches.
**Approach 1 : O(n^2) O(1)
Approach 2 : O(n) O(2n)
Approach 3 : O(n) O(1)**

### PR DESCRIPTION
**Pull request by sumitvajarinkar**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes, I read it and follow the same.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

closes #443
I added the Trapping rainwater problem using 3 approaches in C++

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Instead of putting numbers in brackets, rename the file as trapping_rain_water_brute_force.cpp and trapping_rain_water_extra_space.cpp and trapping_rain_water_two_pointer.cpp. 

Great work, just make these changes.

**Review by sumitvajarinkar — COMMENTED** [review]
Thanks ! 
Renamed all approaches as suggested.

**Comment by Saviour1001** [comment]
Great work @sumitvajarinkar !!

**Comment by sumitvajarinkar** [comment]
Thanks @Saviour1001

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
