### PR TITLE
Library Section is added

### PR DESCRIPTION
**Pull request by Swayam933**
@smv1999 **I added some Java books (under dropdown menu) under Library section. But no worry Books on Java, Python, C, C++ and blogs,courses are coming. I will add those. This is just for review. After this PR got merged successfully. I will add those.**

and also add a form, by which others can request anything that they want.

previously created Issue: #231 

Thank you @smv1999

### CODE REVIEW

**Comment by Saviour1001** [comment]
Looks good to me!! Could you review it again @smv1999

**Review by smv1999 — CHANGES_REQUESTED** [review]
Yeah, it is good. Just correct the alignment.

**Comment by Swayam933** [comment]
@smv1999 which one ? I mean alignment of which ?

**Comment by smv1999** [comment]
> @smv1999 which one ? I mean alignment of which ?

Alignment of images inside the grid in README.md.

**Review by Swayam933 — COMMENTED** [review]
alignment fixed @smv1999 
image

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
