### PR TITLE
Check Password strength 

### PR DESCRIPTION
**Pull request by RC2208**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

yes
### Description
Checking strength of password 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#660 
## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Delete the file Data Structures/Queues/circular queue.c which is not part of this PR.

**Comment by RC2208** [comment]
Done

**Review by smv1999 — CHANGES_REQUESTED** [review]
Just add the problem description at the top of the file.

**Comment by RC2208** [comment]
Done.

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
