### PR TITLE
Added solution to leetcode 3 in cpp

### PR DESCRIPTION
**Pull request by nidhisethi88**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Delete the docx file and rename the cpp file as length_of_longest_substring_without_repeat_char.cpp 

And also add comments wherever necessary to explain your core logic.

**Comment by smv1999** [comment]
Also, always mention the issues to which this PR is associated.

**Comment by nidhisethi88** [comment]
okay
thankyou!

**Review by smv1999 — CHANGES_REQUESTED** [review]
Delete the file without the extension "Length of longest substring without repeating characters ".

**Comment by nidhisethi88** [comment]
Deleted that file. What to do next?

**Comment by Saviour1001** [comment]
Great work @nidhisethi88 but I would suggest you to read some other PRs which are already merged so you could understand the workflow better and make more PRs easily !!

**Comment by nidhisethi88** [comment]
okay! thanks!!

**Pull request merged**
