### PR TITLE
added combinational sum

### LINKED ISSUE #320: Combinational Sum in Python
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Yes, it is a new feature

**Describe the solution you'd like**
It is a backtracking problem and I would like to add my solution

**Additional context**
Please assign this issue to me

### PR DESCRIPTION
**Pull request by bhagyashree-06**
fixes #320

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Great. Just add comments wherever necessary to explain why you have done certain things.

**Comment by bhagyashree-06** [comment]
I have updated the commit, kindly check.

**Review by smv1999 — APPROVED** [review]

**Review by smv1999 — CHANGES_REQUESTED** [review]
I think the approach that you have used isn't Backtracking. Kindly place it in an appropriate folder.

**Review by smv1999 — COMMENTED** [review]
Also, I am getting an error executing it : 
Wrong Answer
Details 
Input
[2]
1
Output
[[]]
Expected
[]

**Comment by bhagyashree-06** [comment]
> Also, I am getting an error executing it :
> Wrong Answer
> Details
> Input
> [2]
> 1
> Output
> [[]]
> Expected
> []

Fixed the error and moved to General Questions folder, kindly check.

**Review by smv1999 — CHANGES_REQUESTED** [review]
Are all the test cases passing on LeetCode. Because when I try to submit the solution, it shows wrong answer. There appears to be some error in your logic.

**Comment by bhagyashree-06** [comment]
all test cases are passing on InterviewBit

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
