### PR TITLE
Bellman Ford Algorithm in C

### PR DESCRIPTION
**Pull request by ushmita4**
#496

### CODE REVIEW

**Review by smv1999 — COMMENTED** [review]
Add some comments to explain your core logic.

**Comment by ushmita4** [comment]
Sir, I have made the required changes.

**Comment by ushmita4** [comment]
> Add some comments to explain your core logic. 

Sir I have made the changes yesterday itself.

**Comment by Saviour1001** [comment]
Could you just add the explanation of the Bellman Ford Algorithm at the top of the file, make the explanation as if a novice person might get an idea, you are free to add some links as well.

**Pull request merged**
