### PR TITLE
Left rotate array by D in C++

### LINKED ISSUE #548: Left rotate by D times in C++
## 🚀 Feature

**Left rotate by D [Leetcode](https://leetcode.com/problems/rotate-array/)**
_Medium level_

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

I have 3 approaches to solve this problem.
1.Brute force
2.Extra space
3.No extra space

### PR DESCRIPTION
**Pull request by sumitvajarinkar**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
Closes #548
Left rotate array by D in Cpp - 3 approaches
1. Brute force
2. Extra space
3. No extra space

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Great. Just delete the towerOfHanoi.java file which is not related to this PR.

**Comment by smv1999** [comment]
By the way, what is the issue associated with this PR ?

**Comment by sumitvajarinkar** [comment]
> By the way, what is the issue associated with this PR ?

I was unable to push it in forked repo from VS code.
So, I drag and drop the code in forked repo and merged it.
Mistakenly another java file also get merged.
I fixed it now. 👍

**Comment by sumitvajarinkar** [comment]
> Great. Just delete the towerOfHanoi.java file which is not related to this PR.

Done 👍

**Comment by Saviour1001** [comment]
Mention the issue solved by this PR.

**Comment by sumitvajarinkar** [comment]
> Mention the issue solved by this PR.

Updated 👍 #548

**Comment by Saviour1001** [comment]
@sumitvajarinkar The issue is already closed. And you could only merge PR in one issue. Raise a new issue and connect this PR to that new issue.

**Comment by sumitvajarinkar** [comment]
> @sumitvajarinkar The issue is already closed. And you could only merge PR in one issue. Raise a new issue and connect this PR to that new issue.
So, I need to create a new issue. but how I can connect this?

**Comment by sumitvajarinkar** [comment]
> @sumitvajarinkar The issue is already closed. And you could only merge PR in one issue. Raise a new issue and connect this PR to that new issue.

I reopen that issue. is it okay ?

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
