### PR TITLE
Added maximal square question

### PR DESCRIPTION
**Pull request by AbhiC7721**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

I have read all the contributing guidelines for the repository

### Description
I have provided a detailed description and solution to the problem maximal square on leetcode along with example. The solution is written in C++.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Solves issue #335

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Just place some comments to explain why you have done certain things in your implementation.

**Comment by AbhiC7721** [comment]
@smv1999 Do you mean I should place comments alongside code, as I have explained my approach above and then written the solution.

**Comment by Saviour1001** [comment]
Yes @AbhiC7721 explain the functions and some more parts alongside code, write short points though. No big paragraphs

**Comment by smv1999** [comment]
Yes @AbhiC7721, instead of paragraph, write the comments alongside the code.

**Comment by AbhiC7721** [comment]
Fixed the changes requested and placed the comments in between code

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
