### PR TITLE
Add Fair Playoff Codeforces Solution

### PR DESCRIPTION
**Pull request by ri-tae-ka**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Description

I have added the solution to the Fair Playoff Codeforces question in the Arrays Folder.

### Checklist

- [✅] I've read the contribution guidelines.
- [✅] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#541

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Comment by smv1999** [comment]
What issue is fixed by this PR? Each PR must be associated with an issue. Please go through the contributing guidelines.

**Comment by smv1999** [comment]
Related issue : #541 . Link the correct issue.

**Review by smv1999 — CHANGES_REQUESTED** [review]
Just add some comments wherever necessary to explain your core logic

**Comment by ri-tae-ka** [comment]
Kindly review the changes made.

**Review by smv1999 — CHANGES_REQUESTED** [review]
Great. Just one more change, add the problem description on the top of the file.

**Comment by ri-tae-ka** [comment]
Updated the file with the requested changes. Please review.

**Review by smv1999 — APPROVED** [review]

**Comment by ri-tae-ka** [comment]
@smv1999 Since it was under DCP do i need to fill a form after successful merging of PR.
If so please do share the form with me. :)

**Comment by smv1999** [comment]
Yes, you need to fill the form. The form link is there above in the PR template itself.

**Pull request merged**
