### PR TITLE
The position pairs to get the sum query.

### LINKED ISSUE #758: Sum
Problem Statement : Find possible position pairs the array data entered whose sum result  will be equal to
                                  the query element you entered . 
                                   ex : Elements : 2 3 4 5 
                                           Query : 8
                                           Output :  Addition of elements present at position 2 and 4 = 8.

I will do this in c ++ .
Please assign it to me under DCP'21 .
/assign

### LINKED ISSUE #767: The position Pairs to get the sum query.
Problem Statement : Find possible position pairs the array data entered whose sum result will be equal to
the query element you entered .
ex : Elements : 2 3 4 5
Query : 8
Output : Addition of elements present at position 2 and 4 = 8.

Please assign it to me under DCP'21 .

### PR DESCRIPTION
**Pull request by Mayuri-cell**
closes #767

### CODE REVIEW

**Comment by Saviour1001** [comment]
Mention the correct issue. This issue is already closed by you. Else you can open new issue.

**Comment by Mayuri-cell** [comment]
Issue is reopened .

**Comment by Saviour1001** [comment]
you can't have 2 PRs merged for the same issue, I get that you are adding different languages but make a new issue. The workflow is set to open one issue per PR. Make a new issue for that.

**Comment by Mayuri-cell** [comment]
I have created a new issue .
Please review.

**Comment by Saviour1001** [comment]
Fixes issue #767

**Pull request merged**
