### PR TITLE
Create GCD SUMs.cpp

### PR DESCRIPTION
**Pull request by vanishasamriddhi**
Issue #275 
Problem Link: https://www.codechef.com/problems/SUMGCD

### CODE REVIEW

**Comment by Saviour1001** [comment]
@vanishasamriddhi could you please add comments and explain the code. Add the space and time complexities.

**Comment by vanishasamriddhi** [comment]
@Saviour1001 I'm working on it. Thank you letting me know about it.

**Comment by vanishasamriddhi** [comment]
Do check the update!

**Comment by Saviour1001** [comment]
@vanishasamriddhi you do realise that this question bank is used by people to revise the questions for their interview preparation and also revising some questions. Now consider reading your code file from a user perspective. He doesn't know what the question is, he doesn't know what is the intuition. 
What you should do, is add the link to the question in the comments, explain it a little. Pitch your idea to solve it and then write the code. 

Remember writing code is not hard, writing code which can be explained to multiple people does take practice. 
Work on the points I just described and make the changes. The code is correct but now you need to make it more readable and self explanatory.

**Pull request closed without merging**
