### PR TITLE
Closes #819 : DSA & Python Basics

### LINKED ISSUE #819: DSA & Python basics
## 💥 Proposal

I will be adding assignments question that I had used as a bigger to master data structure also coding question and solutions of Python basics (Including linked list, pattern, tree). 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### PR DESCRIPTION
**Pull request by PrashantVIT1**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Description

The DSA & Python basics contains coding question that are basics of Data Structure and easy to understand it contains the code that I had done when I was a beginner and the codes are in very easy format and can be easily understood.   

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
Closes #819

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Comment by Saviour1001** [comment]
@PrashantVIT1 this is a very big PR and the codes you are adding, some of them are already present in the repository. As we don't want your work to go in vain, could you make separate issues and separate files for each and every file you want to add. Do give a check if it is already there.

**Comment by PrashantVIT1** [comment]
ok @Saviour1001 can you comment on problems that are present and I guess the may be some of the problems code be same but I have done the coding so may be this codes can be considered as different approach I guess as it was   mentioned in Contributing Guidelines on Pull Requests as please do comment which problems are same and what changes I will have to make while rising another PR request

**Comment by Saviour1001** [comment]
@PrashantVIT1 like [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/tree/master/Data%20Structures) we have a lot of Data Structures already, which are implemented in various languages. Find some concepts which are not present and add them. 
For example the Trie Data Structure is only present in CPP yet, so you can implement it in python. 
Your workflow would be 
- Raise an issue stating you want to add Trie in Python 
- Make a PR consisting of only one file which will be implementation of Trie. 

Just add one problem in each issue and one file in each PR solving that specific issue. 

I am closing this PR and issue for now, you could start working on a new one.

**Comment by PrashantVIT1** [comment]
ok thanks

**Pull request closed without merging**
