### PR TITLE
General Question Added [LeetCode Problem]

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hello,

This PR to add a new general question for a `LeetCode` problem.

I hope this help other developers.

Thanks

### CODE REVIEW

**Review by smv1999 — APPROVED** [review]
Looks good to me :)

**Comment by TawfikYasser** [comment]
> Looks good to me :)

Thanks @smv1999

**Comment by smv1999** [comment]
@TawfikYasser Please note that it is always recommended to commit to a new branch instead of master (main) branch and then push your changes and make a PR. Please refer to [Contributing Guidelines](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md) if you need help in this regard.

**Comment by TawfikYasser** [comment]
> @TawfikYasser Please note that it is always recommended to commit to a new branch instead of master (main) branch and then push your changes and make a PR. Please refer to [Contributing Guidelines](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md) if you need help in this regard.

Sorry for that, I will consider it next time.

**Comment by smv1999** [comment]
No problem @TawfikYasser . Please make a note of this for the next PR that you make.

**Pull request merged**
