### PR TITLE
Climbing Stairs in C++

### PR DESCRIPTION
**Pull request by Ayonijakaushik19**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Description

Climbing Stairs solution in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#587 Climbing Stairs C++

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Delete the file "Merge Two Sorted Array.cpp " which is not related to this PR.

**Comment by noviicee** [comment]
@Ayonijakaushik19 this issue is assigned to someone else, you can't contribute to it. Either you have to ask for assigning it to you if you see an inactivity, or could assign the non assigned issues to yourself, or create new issues. :)

**Review by noviicee — COMMENTED** [review]
@Ayonijakaushik19 this issue is assigned to someone else, you can't contribute to it. Either you have to ask for assigning it to you if you see an inactivity, or could assign the non assigned issues to yourself, or create new issues. :)

**Comment by noviicee** [comment]
@Ayonijakaushik19 remove the extra files which are not relevant from this PR.

**Pull request closed without merging**
