### PR TITLE
Added Truck tour problem (Hackerrank)

### PR DESCRIPTION
**Pull request by Karnika06**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes, I have.

### Description

Added this problem to Queue folder  since this problem uses Circular Queue.
Link to the problem: https://www.hackerrank.com/challenges/truck-tour/problem

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Fixes issue no. #806 

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Just remove the empty files that are not related to this PR.

**Comment by Karnika06** [comment]
I'm sorry, I didn't realized there are empty files.

**Review by noviicee — COMMENTED** [review]
Good work @Karnika06 .

**Comment by Karnika06** [comment]
Thank you @noviicee

**Comment by Karnika06** [comment]
@smv1999 now can you please remove the **changes requested** label from this PR.

**Pull request merged**
