### PR TITLE
Array Reversal added

### PR DESCRIPTION
**Pull request by UG-SEP**
# Hey👋👋,
## I have added _**Array Reversal**_ Program in Array Folder..
I Have readed the [contributing.md](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)
and follow the rules..
```javascript
if(you Love)
{
Thanks for let me to contribute😊😊
Happy Coding! 👨‍💻
}
```

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Place the comments above the statements instead of at the side.

**Comment by UG-SEP** [comment]
ok
😀

**Comment by UG-SEP** [comment]
done the changes

**Review by smv1999 — APPROVED** [review]
Looks good to me :)

**Pull request merged**
