### PR TITLE
Trapping rain water problem using c++(Optimised)

### PR DESCRIPTION
**Pull request by vishvarana**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Description

The problem is what most amount of rain water can the container store with different heights of the walls given as an array.

### Checklist

-  I've read the contribution guidelines.
-  I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#278 

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Comment by sumitvajarinkar** [comment]
@vishvarana 
I run this solution but I am getting the wrong answer. Can you please check it? 
The correct answer for input n=9, 1,8,6,2,5,4,8,3,7 is 19 and this code answer is 49.

**Comment by vishvarana** [comment]
The maximum heights chosen will be 8 and 7 that is 2nd and last element of the array.
The base will be 8-1=7(index of last element - 2nd element)
Water can only be filled upto the shorter of the two heights or it will overflow
Hence the area will be 7*7(shorter height*base)=49

**Comment by vishvarana** [comment]
The idea is to maximize the area to trap water by both heights as well as base length.

**Comment by vishvarana** [comment]
Smallest distinct window problem using c++
#317 issue

**Comment by vishvarana** [comment]
Please review

**Comment by Saviour1001** [comment]
@vishvarana add comments and explain the question in the code. Also add complexities.

**Comment by vishvarana** [comment]
Trapping the rain water - I have explained the problem in previous comments 
Time complexity - O(n)
Space complexity - O(1)

Smallest distinct window in a string containing all other characters of the string : 
The problem focuses on 2 strings, one is the main, other being a part or substring. The idea is to find all the characters present in the part string in the main string and to print those contents of the string, which has this found characters
Time complexity - O(n^2)
Space complexity - O(1)

**Comment by vishvarana** [comment]
There are 2 solutions added and both explained with complexities.

**Comment by Saviour1001** [comment]
@vishvarana I am asking you to add the description and complexities as comments in the code file.

**Comment by smv1999** [comment]
@vishvarana, Also place the file in appropriate folder.

**Comment by vishvarana** [comment]
Required changes made.
Please review and let me know for any other improvements

**Comment by smv1999** [comment]
> Smallest distinct window problem using c++
> #317 issue

Raise a new PR for #317

**Comment by vishvarana** [comment]
New PR made
#651

**Review by smv1999 — CHANGES_REQUESTED** [review]
Then delete smallestdistinctwindow.cpp  in this PR as it is not related to this. Also, delete the unnecessary (repetitive) files (which are not placed in any folder).

**Comment by vishvarana** [comment]
Required changes done

**Review by smv1999 — CHANGES_REQUESTED** [review]
Great. Just add some comments to explain your core logic.

**Comment by vishvarana** [comment]
Added comments in the cpp file

**Comment by Saviour1001** [comment]
Good work @vishvarana

**Pull request merged**
