### PR TITLE
Create redundant_braces.cpp

### LINKED ISSUE #798: Redundant Braces in C++
## 🚀 Feature

Given a string A denoting an expression. It contains the following operators ’+’, ‘-‘, ‘*’, ‘/’.

Check whether A has redundant braces or not.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

yes

## Motivation

Stack implementation

## Pitch

asked in Amazon

### PR DESCRIPTION
**Pull request by ishikasinha-d**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

(Write your answer here.)
Yes

### Description

(Write your answer here.)
Given a string A denoting an expression. It contains the following operators ’+’, ‘-‘, ‘*’, ‘/’.

Check whether A has redundant braces or not.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)
closes #798

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Add some comments to explain your core logic.

**Comment by ishikasinha-d** [comment]
added comments

**Review by noviicee — COMMENTED** [review]
@ishikasinha-d add some test-cases and time-complexity of the program.

**Review by noviicee — COMMENTED** [review]
Looks fine. @ishikasinha-d always try to add the test-cases and time-complexity **below** the code.

**Review by noviicee — APPROVED** [review]
Good work @ishikasinha-d

**Pull request merged**
