### PR TITLE
Updated single linked list python operations

### PR DESCRIPTION
**Pull request by kumarankm**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Description

Updated the python code of singly linked list, where removing is done by using value instead of index

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#601 [Updating singly linked list with python]

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Comment by noviicee** [comment]
@kumarankm please take input from the user.

**Review by noviicee — COMMENTED** [review]
@kumarankm please take input from the user.

**Comment by kumarankm** [comment]
> @kumarankm please take input from the user.

Yeah sure, but for all those previous operations they didn't take input dynamically @noviicee

**Comment by kumarankm** [comment]
@noviicee Done 👍🏻

**Review by noviicee — COMMENTED** [review]
Add a case in the removal method when the value passed for removal is not present in the Linked List.

**Comment by kumarankm** [comment]
> Add a case in the removal method when the value passed for removal is not present in the Linked List.

@noviicee  Added 👍🏻

**Comment by noviicee** [comment]
@kumarankm please take dynamic input from the user to insert values and form a linked list. Rest the processes look fine so far.

**Comment by kumarankm** [comment]
> @kumarankm please take dynamic input from the user to insert values and form a linked list. Rest the methods look fine so far.

@noviicee  Changed 👍🏻  Got a dynamic input for every single operation 🤓

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
