### PR TITLE
Cycle detection in linked list using python

### PR DESCRIPTION
**Pull request by kumarankm**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Description

Added a code that detects if there is any cycle detection in the linked list using python

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Cycle detection in linked list python
Issue: #842

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Remove the file "merge_two_sorted_linkedlist.py " which is not related to this PR.

**Comment by kumarankm** [comment]
> Remove the file "merge_two_sorted_linkedlist.py " which is not related to this PR.

@smv1999 Done 👍🏻

**Comment by smv1999** [comment]
It seems that there are some conflicts that need to resolved from your end @kumarankm . Please look into that.

**Comment by kumarankm** [comment]
> It seems that there are some conflicts that need to resolved from your end @kumarankm . Please look into that.

@smv1999  My resolve conflicts button is hidden. 
image

**Comment by Saviour1001** [comment]
Hey @kumarankm , I tried merging the PR locally as well but wasn't able to resolve the merge conflicts,So I am closing this PR for now, could you open a new one

**Pull request closed without merging**
