### PR TITLE
Create factorial-of-a-number.c

### PR DESCRIPTION
**Pull request by Ayush7614**

### CODE REVIEW

**Comment by Ayush7614** [comment]
@smv1999 sir plss review it

**Review by smv1999 — CHANGES_REQUESTED** [review]
@Ayush7614 Place the recursion version of the program in a separate file. Call that "factorial_of_a_number_recursion.c" and commit the changes.

**Comment by Ayush7614** [comment]
okk sir i will do it

**Comment by Ayush7614** [comment]
Now sir you can review it

**Review by smv1999 — APPROVED** [review]
Looks good to me :)

**Pull request merged**
