### PR TITLE
Kth smallest element in an array

### PR DESCRIPTION
**Pull request by divyaachoudharyy**
It can be made simple by using a heap which reduces the time complexity from the brute force approach O(n^2) to O(n).

### CODE REVIEW

**Comment by smv1999** [comment]
There is no issue associated with this PR. Each PR should be associated with an issue.

**Comment by Saviour1001** [comment]
@divyaachoudharyy please mention the issue to which this PR is addressed.

**Comment by divyaachoudharyy** [comment]
Hey! I have made a PR and after making a PR how should I rause an issue. I
am quite new to github so don’t have the proper knowledge of how things
work.

Thank you.

**Comment by Saviour1001** [comment]
@divyaachoudharyy The workflow of the open-source contribution is raising an issue first, and then making the PR regarding that. You can't just open random PRs about anything.
What you can do now is make an issue regarding what you did in this PR, and link that issue here by mentioning its number 
#<number of issue> 
This will link the issue and the PR , and then it can be reviewed for further procedure

**Comment by divyaachoudharyy** [comment]
Thanks, I'll do the same.

**Comment by divyaachoudharyy** [comment]
Hey, I raised an issue regarding what I wanted to add, however it is
showing me this error. Would you mind helping me out with this?

**Comment by smv1999** [comment]
What error @divyaachoudharyy ?

**Comment by Saviour1001** [comment]
@divyaachoudharyy it would be great if you could send a screenshot on Slack or over here, so that we could help you out!

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
