### PR TITLE
gcd of two number by for loop

### PR DESCRIPTION
**Pull request by gaurav24072002**
I have made a program to calculate gcd of two number by using for loop...

### CODE REVIEW

**Review by smv1999 — COMMENTED** [review]
@gaurav24072002 GCD of two numbers program is already present. Check [this](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/tree/master/GCD%20of%20two%20numbers). Please make sure to check the existing programs before adding new ones.
Happy Coding!

**Comment by gaurav24072002** [comment]
But I have made gcd by use of for loop and your repository have normal gcd with if-else and while loop

**Comment by smv1999** [comment]
Yes I understand @gaurav24072002 . Only the syntax changes but the logic remains the same. Right?
You are welcome to work on problems in other topics. Looking forward to your contributions.

**Comment by gaurav24072002** [comment]
Yeah sure I'll do them😊

**Comment by smv1999** [comment]
Also, you can have look at the existing issues to get an idea. https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues

**Pull request closed without merging**
