### PR TITLE
Added Permutation of string

### PR DESCRIPTION
**Pull request by UG-SEP**
hey, 
I have Added Permutation of string in string folder please review it ..
Well I have readed the contributing.md 
Issue : #3

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
Use a formatting tool to format your code.

**Comment by UG-SEP** [comment]
hey @smv1999  please check it

**Review by smv1999 — CHANGES_REQUESTED** [review]
When the suggested changes were made, the output of the program has changed as well. Please verify and validate the output and submit again.

**Comment by UG-SEP** [comment]
> When the suggested changes were made, the output of the program has changed as well. Please verify and validate the output and submit again.

I can't able to to understand the difference between output of the program 
Screenshot 2021-04-04 193345
Screenshot 2021-04-04 193415
Screenshot 2021-04-04 193509

**Review by smv1999 — COMMENTED** [review]
I will look into it and revert .

**Comment by UG-SEP** [comment]
ok

**Comment by smv1999** [comment]
When I run the program, I am getting the output like this !
image

**Comment by UG-SEP** [comment]
what 😲🤪🤪 well ok i will check this program i think i should close this pull request right now

**Pull request closed without merging**
