### PR TITLE
Added Combinal Sum Problem

### LINKED ISSUE #268: Backtracking Questions
I want to add few Backtracking problems ( Combinational Sum, Subset sum problem, Permutations of a String etc. ) in Python3

Can you assign me this issue ?

### PR DESCRIPTION
**Pull request by bhagyashree-06**
fixes #268

### CODE REVIEW

**Comment by Saviour1001** [comment]
@bhagyashree-06 Please make one PR for one file, if you contribute multiple files in a single file, you will still be awarded for only one PR, We don't want to cause such problems for you. Please raise one issue for one question and one PR regarding that issue.

**Comment by bhagyashree-06** [comment]
> @bhagyashree-06 Please make one PR for one file, if you contribute multiple files in a single file, you will still be awarded for only one PR, We don't want to cause such problems for you. Please raise one issue for one question and one PR regarding that issue.

Oh okay ! 
so, should I create a new PR now ? or will these files be merged with the master branch ?

**Comment by Saviour1001** [comment]
Create multiple issues for multiple questions, one question per issue. And similarly one issue per PR.

**Comment by bhagyashree-06** [comment]
okay, got it 
thanks.

**Pull request closed without merging**
