### PR TITLE
Created Board.java

### PR DESCRIPTION
**Pull request by hridaya423**
It includes two files
Board.java
Snake.java
Please review it @smv1999

### CODE REVIEW

**Comment by smv1999** [comment]
Don't create separate PR for each and every file. Instead commit them all once and make a single PR. Also, please make sure you are not adding any program which is already present. Refer to [this](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md) and follow the guidelines.

**Comment by smv1999** [comment]
Closed #32 , #33 , #34 , #35 , #36 , #37 , #38 , #39 , #40 for the same above stated reason.

**Comment by hridaya423** [comment]
You mean I should make all in 1 pull request?

**Comment by hridaya423** [comment]
And actually, I didn't make any duplicates!
I made java programs there are none of the java programs in this

**Comment by hridaya423** [comment]
How to make all in one pull request? Any guide?

**Pull request closed without merging**
