### PR TITLE
Added Bridge edge in Graph problem

### LINKED ISSUE #880: Bridge Edge in graph
# Aim
126879051-7f147b5f-af36-4e1d-aa5b-c9a6db340e1e

# Details
I would like to solve this problem in C++ language.

### PR DESCRIPTION
**Pull request by Karnika06**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes.

### Description

**Problem statement:** 
Given an undirected graph of V vertices and E edges and another edge (c-d), the task is to 
find if the given edge is a bridge in graph, i.e., removing the edge disconnects the graph.

Link to the problem: https://practice.geeksforgeeks.org/problems/bridge-edge-in-graph/1

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Fixes #880 

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual. 

Please review this PR and merge it.

### CODE REVIEW

**Comment by Karnika06** [comment]
Please review this PR @smv1999

**Review by noviicee — CHANGES_REQUESTED** [review]
Remove the extra files which are not related to this PR.

**Comment by Karnika06** [comment]
hello @noviicee , I am sorry but I am not able to get which extra files I have to delete. I have checked twice and I haven't got any extra files. Can you please help me which file I have to delete?

**Comment by smv1999** [comment]
Remove the file "Codechef Problems/MaximumArrayXOR.java" which is not related to this PR.

**Comment by Karnika06** [comment]
Okay, now check

**Review by smv1999 — APPROVED** [review]

**Pull request merged**
