### PR TITLE
added palindrome and DLL reverse for linked list

### PR DESCRIPTION
**Pull request by version0chiro**
## Added two questions under linked list data structure. 

- One checking if the linked list is palindrome or not.
- Other one for reversing a doubly linked list.

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
The "check_if_linkedlist_is_a_palindrome" solution is great as you have used a different approach than [this](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Data%20Structures/Linked%20Lists/check_linkedlist_palindrome.cpp). 
Please give a brief description of your approach at the top of the file. 

Also for reverse_a_double_linkedlist program add a description of the problem and add comments wherever necessary above that particular statement. 

Make these changes and you are good to go ! Great work BTW.

**Comment by version0chiro** [comment]
> The "check_if_linkedlist_is_a_palindrome" solution is great as you have used a different approach than [this](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Data%20Structures/Linked%20Lists/check_linkedlist_palindrome.cpp).
> Please give a brief description of your approach at the top of the file.
> 
> Also for reverse_a_double_linkedlist program add a description of the problem and add comments wherever necessary above that particular statement.
> 
> Make these changes and you are good to go ! Great work BTW.


@smv1999  I have made the  requested changes, kindly check the commits.

**Comment by version0chiro** [comment]
@smv1999 I have made the requested changes, kindly check the commits.

**Review by smv1999 — APPROVED** [review]
Looks good to me :)

**Pull request merged**
