### PR TITLE
Added a c program to print if matrices are equal or not

### PR DESCRIPTION
**Pull request by MannyP31**

### CODE REVIEW

**Review by smv1999 — CHANGES_REQUESTED** [review]
The PR includes sorting of an array in ascending order program which has been closed in #86 .

With respect to the "Matrices are equal or not" program, please place the file under the folder "2D Arrays"

Do the necessary changes and resubmit again.

**Comment by MannyP31** [comment]
Okay sure....excuse me for this inconvenience 😅

**Comment by MannyP31** [comment]
> The PR includes sorting of an array in ascending order program which has been closed in #86 .
> 
> With respect to the "Matrices are equal or not" program, please place the file under the folder "2D Arrays"
> 
> Do the necessary changes and resubmit again.



yep now plz have a look i have done the necessary changes

**Review by smv1999 — CHANGES_REQUESTED** [review]
The equal matrices program is fine, but you haven't deleted the array.cpp file. Just make that change and resubmit.

**Comment by MannyP31** [comment]
> The equal matrices program is fine, but you haven't deleted the array.cpp file. Just make that change and resubmit.

yeah i did that too

**Pull request merged**
