### PR TITLE
Create fibonacci-series.c

### PR DESCRIPTION
**Pull request by Ayush7614**

### CODE REVIEW

**Comment by Ayush7614** [comment]
Plss review it @smv1999 sir

**Review by smv1999 — CHANGES_REQUESTED** [review]
@Ayush7614 Instead of creating a new folder named "C". Place the file inside "Numbers"  folder and commit your changes.

**Comment by Ayush7614** [comment]
@smv1999 sir plss review now

**Review by smv1999 — APPROVED** [review]
Looks good to me :)

**Pull request merged**
