### PR TITLE
Create Isomorphic.java

### PR DESCRIPTION
**Pull request by ushmita4**
#731 
Checking whether two strings are isomorphic or not.

Two strings s and t are isomorphic if the characters in s can be replaced to get t.
All occurrences of a character are replaced with another character while preserving the order of characters. No two characters map to the same character, but a character may map to itself.

### CODE REVIEW

**Comment by smv1999** [comment]
The problem already exists [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Hashing/IsomorphicStrings.java). If you are using a different approach, then explain how yours is different.

**Comment by ushmita4** [comment]
> The problem already exists [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Hashing/IsomorphicStrings.java). If you are using a different approach, then explain how yours is different. 

The solution here is of O(n).
The idea is to create an array to store mappings of processed characters.

**Review by noviicee — COMMENTED** [review]
Kindly elaborate @ushmita4

**Comment by ushmita4** [comment]
> Kindly elaborate @ushmita4

1) If lengths of str1 and str2 are not the same, then return false.
2) Here for every character in str1 and str2
   a) If this character is seen the first time in str1, 
      then-current of str2 must have not appeared before.
      (i) If the current character of str2 is seen, return false.
          Mark current character of str2 as visited.
      (ii) Store mapping of current characters.
   b) Else check if the previous occurrence of str1[i] mapped
      to the same character.

**Pull request closed without merging**
